#!/usr/bin/env python
#-*- coding: utf-8 -*-

##################################################################################################
# PROJECT EULER 2                                                                                #
# Each new term in the Fibonacci sequence is generated by adding the previous two terms.         #
# By starting with 1 and 2, the first 10 terms will be:                                          #
#          1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...                                                #
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,    #
# find the sum of the even-valued terms.                                                         #
#                                                                                                #
#                                                                                                #
#                                                                                                #
##################################################################################################

x, y, z = 0, 1, 0
while y < 4000000:
     x, y = y, x + y
     if y % 2 == 0:
         z += y
print z
if __name__ == "__main__":
    import doctest
    doctest.testmod()    


    


